# external packages: time os fmt path template opts http log io/ioutil strings 
compile.a: compile.go data.a 
data.a: data.go 
input.a: input.go data.a 
main: main.${O}
main.${O}: main.go compile.a data.a input.a 
